version: '3.7'

services:

  student-calculator-nginx:
    container_name: student-calculator-nginx
    depends_on:
      - student-calculator-node
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./configs/nginx:/etc/nginx                        # config
      - ./configs/templates-ssl-init:/etc/nginx/templates # init server
      - ${STATIC_PATH}:/static                            # static
      - ${LOGS}:/logs                                     # logs
      - ${ETC_LETSENCRYPT}:/etc/letsencrypt               # ssl config
      - ${WWW_LETSENCRYPT}:/var/www/certbot               # ssl static auth
    environment:
      DOMAIN: ${DOMAIN}
    #command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  student-calculator-certbot:
    container_name: certbot
    depends_on:
      - student-calculator-nginx
    image: certbot/certbot
    volumes:
      - ${ETC_LETSENCRYPT}:/etc/letsencrypt
      - ${WWW_LETSENCRYPT}:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email nigvi-work@mail.ru --agree-tos --no-eff-email -d ${DOMAIN}

  student-calculator-node:
    container_name: student-calculator-node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${STATIC_PATH}:/build/dist